//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.Students1 = new HashSet<Students>();
            this.TeachersGroupsSubjects = new HashSet<TeachersGroupsSubjects>();
            this.TheTasks = new HashSet<TheTasks>();
        }
        public int Id { get; set; }
        public int Number { get; set; }
        public int YearOfAdmission { get; set; }
        public string Faculty { get; set; }
        public string Degree { get; set; }
        public string FormOfStudy { get; set; }
        public Nullable<int> MonitorId { get; set; }
        static public int GetActualGroupNumber(Groups group, int year)
        {
            if (year > group.YearOfAdmission)
            {
                while (year != group.YearOfAdmission)
                {
                    group.Number++;
                    group.YearOfAdmission++;
                }
            }
            return group.Number;
        }
        public virtual Students Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeachersGroupsSubjects> TeachersGroupsSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheTasks> TheTasks { get; set; }
    }
}
