//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableEntry
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int TableOfGradeId { get; set; }
        public string Value { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual TableOfGrades TableOfGrades { get; set; }
    }
}
