//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarySchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheTasks
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public string TaskText { get; set; }
        public int GroupId { get; set; }
        public string Documents { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
